<a href="index.php?menu=1"><font class="menu">[Устройства]</font></a>
<a href="index.php?menu=7"><font class="menu">[Единицы измерения]</font></a>
<a href="index.php?menu=4"><font class="menu">[Данные]</font></a>
<a href="index.php?menu=2"><font class="menu">[Квартиры]</font></a>
<a href="index.php?menu=3"><font class="menu">[Журнал событий]</font></a>
<a href="index.php?menu=7"><font class="menu">[Энергоресурсы]</font></a>
<a href="index.php?menu=9"><font class="menu">[Отчеты]</font></a>
<a href="index.php?menu=5"><font class="menu">[Пользователи]</font></a>
<a href="index.php?menu=6"><font class="menu">[Переменные]</font></a>
<a href="index.php?menu=8"><font class="menu">[Автоконфиг]</font></a>
 
